'use client';

import React from 'react';
import { X, Download, Maximize2, FileText } from 'lucide-react';

interface SpaPreviewModalProps {
    isOpen: boolean;
    onClose: () => void;
    pdfUrl: string | null;
    title?: string;
}

export default function SpaPreviewModal({ isOpen, onClose, pdfUrl, title = "Sale & Purchase Agreement (SPA)" }: SpaPreviewModalProps) {
    if (!isOpen || !pdfUrl) return null;

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 md:p-10 animate-in fade-in duration-300">
            {/* Backdrop */}
            <div
                className="absolute inset-0 bg-background/80 backdrop-blur-md"
                onClick={onClose}
            />

            {/* Modal Content */}
            <div className="relative w-full h-full max-w-6xl bg-card border border-border rounded-2xl shadow-2xl overflow-hidden flex flex-col animate-in zoom-in-95 duration-300">
                {/* Header */}
                <div className="px-6 py-4 border-b border-border flex items-center justify-between bg-card/50 backdrop-blur-sm sticky top-0 z-10">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
                            <FileText className="w-5 h-5 text-primary" />
                        </div>
                        <div>
                            <h3 className="text-lg font-bold text-foreground leading-tight">{title}</h3>
                            <p className="text-xs text-muted-foreground uppercase tracking-widest font-medium">Digital Agreement Preview</p>
                        </div>
                    </div>

                    <div className="flex items-center gap-2">
                        <a
                            href={pdfUrl}
                            download="SPA_Agreement.pdf"
                            className="p-2 hover:bg-secondary rounded-lg transition-colors text-muted-foreground hover:text-foreground"
                            title="Download PDF"
                        >
                            <Download className="w-5 h-5" />
                        </a>
                        <button
                            onClick={onClose}
                            className="p-2 hover:bg-red-500/10 hover:text-red-500 rounded-lg transition-colors text-muted-foreground"
                        >
                            <X className="w-6 h-6" />
                        </button>
                    </div>
                </div>

                {/* PDF Viewer */}
                <div className="flex-1 bg-secondary/30 relative overflow-hidden group">
                    <iframe
                        src={`${pdfUrl}#toolbar=0&navpanes=0&view=FitH`}
                        className="w-full h-full border-none"
                        title="SPA Preview"
                    />

                    {/* Floating Controls for better affordance */}
                    <div className="absolute bottom-6 right-6 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-2">
                        <button
                            onClick={() => window.open(pdfUrl, '_blank')}
                            className="flex items-center gap-2 px-4 py-2 bg-background/80 backdrop-blur-md border border-border rounded-full text-xs font-bold shadow-lg hover:bg-primary hover:text-white hover:border-primary transition-all"
                        >
                            <Maximize2 className="w-3 h-3" />
                            Open in Full Window
                        </button>
                    </div>
                </div>

                {/* Footer / Status */}
                <div className="px-6 py-3 border-t border-border bg-card/50 text-[10px] text-muted-foreground flex justify-between items-center">
                    <p>Generated by DoreMarket Platform Secure Document Engine</p>
                    <div className="flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.5)] anim-pulse" />
                        <span>VERIFIED SECURE DOCUMENT</span>
                    </div>
                </div>
            </div>
        </div>
    );
}
