"use client";
import { Printer } from 'lucide-react';

export default function AgreementView({ agreement }: any) {
    return (
        <div className="bg-white text-black p-12 shadow-lg rounded-sm max-w-[210mm] mx-auto min-h-[297mm] relative print:shadow-none print:w-full">
            <div className="absolute top-4 right-4 print:hidden">
                <button
                    onClick={() => window.print()}
                    className="flex items-center gap-2 px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800"
                >
                    <Printer size={16} /> Print / Save PDF
                </button>
            </div>

            <div className="whitespace-pre-wrap font-serif leading-relaxed text-sm">
                {agreement.terms}
            </div>

            <div className="mt-16 pt-8 border-t border-gray-300 grid grid-cols-2 gap-12">
                <div>
                    <p className="font-bold mb-8">SELLER</p>
                    <div className="h-12 border-b border-black"></div>
                    <p className="text-xs mt-2 text-gray-500">Authorized Signature</p>
                </div>
                <div>
                    <p className="font-bold mb-8">BUYER</p>
                    <div className="h-12 border-b border-black relative">
                        <span className="absolute bottom-2 left-0 font-cursive italic text-xl">
                            {agreement.buyerName} (Digital)
                        </span>
                    </div>
                    <p className="text-xs mt-2 text-gray-500">Authorized Signature</p>
                </div>
            </div>

            <div className="mt-12 text-center text-xs text-gray-400">
                Generated by Dore & Market Platform • Deal ID: {agreement.dealId}
            </div>
        </div>
    );
}
